export const SKILL_SUGGESTIONS = [
  "Python", "JavaScript", "TypeScript", "Java", "C++", "C#", "C", "Go", "Rust", "Ruby",
  "PHP", "Swift", "Kotlin", "Scala", "R", "MATLAB", "SQL", "HTML", "CSS", "Sass",
  "React", "Next.js", "Vue.js", "Angular", "Svelte", "Node.js", "Express.js", "FastAPI",
  "Flask", "Django", "Spring Boot", "Ruby on Rails", "ASP.NET", "Laravel",
  "TailwindCSS", "Bootstrap", "Material UI", "Chakra UI", "shadcn/ui",
  "PostgreSQL", "MySQL", "MongoDB", "Redis", "SQLite", "DynamoDB", "Snowflake",
  "Firebase", "Supabase", "AWS", "Azure", "GCP", "Docker", "Kubernetes", "Terraform",
  "Git", "GitHub Actions", "CI/CD", "Jenkins", "Linux", "Nginx",
  "TensorFlow", "PyTorch", "Scikit-learn", "Pandas", "NumPy", "OpenAI API",
  "LLMs", "Prompt Engineering", "RAG", "LangChain", "Hugging Face",
  "GraphQL", "REST API", "gRPC", "WebSockets", "OAuth", "JWT",
  "Figma", "Adobe XD", "Photoshop", "Illustrator", "Blender",
  "Jira", "Confluence", "Notion", "Slack", "Trello",
  "Agile", "Scrum", "Kanban", "Product Management", "Project Management",
  "Data Analysis", "Data Engineering", "Machine Learning", "Deep Learning",
  "Natural Language Processing", "Computer Vision", "Data Visualization",
  "Power BI", "Tableau", "Looker", "Excel", "Google Sheets",
  "Selenium", "Cypress", "Jest", "Vitest", "Pytest", "JUnit",
  "Postman", "Swagger", "Webpack", "Vite", "Babel", "ESLint",
  "Apache Spark", "Hadoop", "Kafka", "Airflow", "dbt",
  "Solidity", "Web3", "Blockchain",
  "Unity", "Unreal Engine", "Game Development",
  "UI/UX Design", "Wireframing", "Prototyping", "User Research",
  "Technical Writing", "Public Speaking", "Leadership", "Teamwork",
  "Communication", "Problem Solving", "Critical Thinking", "Creativity",
  "Anaconda", "Seaborn", "Matplotlib",
];
